apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sso-demo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Tran8811/dnw7.git
    targetRevision: HEAD
    path: SSO-main/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: sso-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
