# Đường dẫn: helm/coursetracker/templates/servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    # === BẠN CẦN THÊM DÒNG NÀY VÀO ===
    release: prometheus
    # === HẾT PHẦN THÊM VÀO ===

    # Các nhãn này được lấy từ _helpers.tpl
    {{- include "coursetracker.labels" . | nindent 4 }}
spec:
  # Bộ chọn (selector) này phải khớp với nhãn (labels) trên file service.yaml
  selector:
    matchLabels:
      {{- include "coursetracker.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s