# Staging environment values
replicaCount: 1

image:
  repository: ghcr.io/your-username/coursetracker
  tag: "develop"

service:
  type: NodePort
  port: 8080
  nodePort: 30081

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

configMap:
  database:
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password: ""
  hibernate:
    ddlAuto: "create-drop"
  h2:
    consoleEnabled: "true"
    consolePath: "/h2-console"
