apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: sso-demo
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:21.1.1
        args: ["start-dev"]
        env:
          - name: KEYCLOAK_ADMIN
            value: admin
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-keycloak-secrets
                key: KEYCLOAK_ADMIN_PASSWORD
          - name: KC_DB
            value: mysql
          - name: KC_DB_URL
            value: jdbc:mysql://mysql:3306/keycloak
          - name: KC_DB_USERNAME
            value: appuser
          - name: KC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-keycloak-secrets
                key: MYSQL_PASSWORD
          - name: KC_HTTP_ENABLED
            value: "true"
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 160
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
