apiVersion: v1
kind: Secret
metadata:
  name: mysql-keycloak-secrets
  namespace: sso-demo
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword123       # đổi nếu cần
  MYSQL_PASSWORD: app-password123            # password cho appuser
  KEYCLOAK_ADMIN_PASSWORD: kc-admin-pass123  # Keycloak admin password
