# Đường dẫn: .github/workflows/ci-cd.yml
# (Nằm trong repo tran8811/dnw7)

name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # tran8811/dnw7

jobs:
  # --- CÁC JOB test, build-and-push, security-scan GIỮ NGUYÊN ---
  # (Tôi sẽ rút gọn các job này, chỉ giữ lại phần deploy đã sửa)

  test:
    runs-on: ubuntu-latest
    permissions:      # <--- THÊM KHỐI NÀY
      contents: read    # Quyền để checkout code
      checks: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Make gradlew executable
      run: chmod +x CourseTracker-main/demo1/gradlew
    - name: Run tests
      run: |
        cd CourseTracker-main/demo1
        ./gradlew test
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Gradle Tests
        path: CourseTracker-main/demo1/build/test-results/test/TEST-*.xml
        reporter: java-junit

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Make gradlew executable
      run: chmod +x CourseTracker-main/demo1/gradlew
    - name: Build application
      run: |
        cd CourseTracker-main/demo1
        ./gradlew build -x test
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./CourseTracker-main/demo1
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  security-scan:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        format: 'sarif'
        output: 'trivy-results.sarif'
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  # --- PHẦN DEPLOY ĐÃ SỬA CHO MONO-REPO ---
  
  update-config-staging:
    needs: [build-and-push, security-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' # Kích hoạt khi push lên 'develop'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Cần token để push commit trở lại repo
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update image tag for staging
      run: |
        # Sửa file values-staging.yaml ngay trong repo này
        sed -i "s|tag: .*|tag: ${{ github.sha }}|g" helm/coursetracker/values-staging.yaml
        
        # Commit và push
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        # Thêm [skip ci] để tránh lặp vô tận pipeline
        git commit -am "Update staging image to ${{ github.sha }} [skip ci]"
        git push

  update-config-production:
    needs: [build-and-push, security-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Kích hoạt khi push lên 'main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Cần token để push commit trở lại repo
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update image tag for production
      run: |
        # Sửa file values-production.yaml ngay trong repo này
        sed -i "s|tag: .*|tag: ${{ github.sha }}|g" helm/coursetracker/values-production.yaml
        
        # Commit và push
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        # Thêm [skip ci] để tránh lặp vô tận pipeline
        git commit -am "Update production image to ${{ github.sha }} [skip ci]"
        git push
  notify:
    needs: [update-config-staging, update-config-production]
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Notify deployment status
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        # DÒNG 'webhook_url' ĐÃ BỊ XÓA KHỎI ĐÂY
      env:
        # Dòng này là ĐÚNG và cần giữ lại
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}