# Đường dẫn: .github/workflows/ci-cd.yml
# (Nằm trong repo tran81/dnw7)

name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # tran8811/dnw7

jobs:
  # --- CÁC JOB test, build-and-push, security-scan GIỮ NGUYÊN ---
  # (Tôi sẽ rút gọn các job này, chỉ giữ lại phần deploy đã sửa)

  test:
    runs-on: ubuntu-latest
    permissions:      # <--- THÊM KHỐI NÀY
      contents: read    # Quyền để checkout code
      checks: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Make gradlew executable
      run: chmod +x CourseTracker-main/demo1/gradlew
    - name: Run tests
      run: |
        cd CourseTracker-main/demo1
        ./gradlew test
    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Gradle Tests
        path: CourseTracker-main/demo1/build/test-results/test/TEST-*.xml
        reporter: java-junit

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Make gradlew executable
      run: chmod +x CourseTracker-main/demo1/gradlew
    - name: Build application
      run: |
        cd CourseTracker-main/demo1
        ./gradlew build -x test
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,prefix=,suffix=
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./CourseTracker-main/demo1
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  security-scan:
   needs: build-and-push
  runs-on: ubuntu-latest
  permissions:
    contents: read
    security-events: write
  steps:
   - name: Checkout code
    uses: actions/checkout@v4

   - name: Run Trivy vulnerability scanner
    uses: aquasecurity/trivy-action@master
    with:
      image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
      format: 'sarif'
      output: 'trivy-results.sarif'

   - name: Upload Trivy scan results to GitHub Security tab
    uses: github/codeql-action/upload-sarif@v3
    if: success()
    with:
      sarif_file: 'trivy-results.sarif'
