apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursetracker-app
  labels:
    app: coursetracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coursetracker
  template:
    metadata:
      labels:
        app: coursetracker
    spec:
      containers:
      - name: coursetracker
        image: coursetracker:latest
        imagePullPolicy: Never  # Sử dụng image local
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: coursetracker-config
              key: database.url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: coursetracker-config
              key: database.username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: coursetracker-config
              key: database.password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: coursetracker-config
              key: hibernate.ddl-auto
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
