apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- persistent-volume.yaml
- persistent-volume-claim.yaml
- deployment.yaml
- service.yaml

commonLabels:
  app: coursetracker
  version: v1.0.0

images:
- name: coursetracker
  newTag: latest
